<a href="https://colab.research.google.com/github/shannu1063/shanmukhavarma_INFO5731_Fall2024/blob/main/Kothapalli_ShanmukhaVarma_Exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of Friday, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

## Question 1 (10 Points)
Describe an interesting **text classification or text mining task** and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features. **Your dataset must be text.**

In [1]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Task: Analysis of sentiment on Movie Reviews

Here, we are classifying if a review of the movie is positive or negative. It is a very common Natural Language Processing (NLP) text classification problem. The dataset will have few text reviews, and we will assign a "positive" or "negative" label.

Some Features we are trying to extract:
Bag of Words (BoW):

This feature helps in finding umber of times a word occured not considering the order.
Why helpful: High-frequency words helps us to know the strong sentiment information, and words like "great" or "terrible" are indicates sentiment.

TF-IDF (Term Frequency-Inverse Document Frequency):

This feature re-adjusts the words frequency based on how commonly they are occuring because words like "the" or "and" are not that important in knowing the sentiment and should be down-weighted.
Why helpful: To get to know more meaningful words by reducing the importance of common words.

Sentiment Lexicon Scores:

Assigning an already existing sentiment lexicon (like AFINN or VADER) score to the review
Why helpful: Lexicons help in identifying sentiment-laden words and give overall sentiment of the document

Part of Speech (POS) Tagging:

Gives grammatical structure of the text, like nouns, pronouns, adjectives, verbs, adverbs.
Why helpful: Adjectives are the most important sentiment-bearing words like "good," "bad," or "beautiful" helps in classification of sentiment.

N-grams (Bigrams and Trigrams):

Analyzing two or three words (bigrams or trigrams) together collectively. For example, "not good" is more informative than "good."
Why helpful: Some statements should be captured based on context (like "not good" vs. "good").



'''

'\nPlease write you answer here:\n\nTask: Analysis of sentiment on Movie Reviews\n\nHere, we are classifying if a review of the movie is positive or negative. It is a very common Natural Language Processing (NLP) text classification problem. The dataset will have few text reviews, and we will assign a "positive" or "negative" label.\n\nSome Features we are trying to extract:\nBag of Words (BoW):\n\nThis feature helps in finding umber of times a word occured not considering the order.\nWhy helpful: High-frequency words helps us to know the strong sentiment information, and words like "great" or "terrible" are indicates sentiment.\n\nTF-IDF (Term Frequency-Inverse Document Frequency):\n\nThis feature re-adjusts the words frequency based on how commonly they are occuring because words like "the" or "and" are not that important in knowing the sentiment and should be down-weighted.\nWhy helpful: To get to know more meaningful words by reducing the importance of common words.\n\nSentiment Le

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [2]:
# You code here (Please add comments in the code):

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk import pos_tag, word_tokenize
from sklearn.feature_extraction.text import TfidfTransformer
import nltk

# Few sample data
texts = [
    "The movie was fantastic and I loved it!",
    "It was a terrible film, really disappointing.",
    "Not good, I wouldn't recommend it to anyone."
]

#Feature Extraction
# 1. Bag of Words (BoW)
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(texts)
print("Bag of Words Feature Matrix:\n", X_bow.toarray())
print("BoW Feature Names:\n", vectorizer.get_feature_names_out())

# 2. TF-IDF
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(texts)
print("TF-IDF Feature Matrix:\n", X_tfidf.toarray())
print("TF-IDF Feature Names:\n", tfidf_vectorizer.get_feature_names_out())

# 3. Sentiment Lexicon Scores using VADER
nltk.download('vader_lexicon')
sid = SentimentIntensityAnalyzer()
for text in texts:
    sentiment_score = sid.polarity_scores(text)
    print(f"Sentiment score for '{text}':", sentiment_score)

# 4. Tagging of Part of Speech (POS)
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
for text in texts:
    tokens = word_tokenize(text)
    pos_tags = pos_tag(tokens)
    print(f"POS Tags for '{text}':", pos_tags)

# 5. N-grams (Bigrams)
vectorizer_ngrams = CountVectorizer(ngram_range=(2, 2))
X_bigrams = vectorizer_ngrams.fit_transform(texts)
print("Bigrams Feature Matrix:\n", X_bigrams.toarray())
print("Bigrams Feature Names:\n", vectorizer_ngrams.get_feature_names_out())



Bag of Words Feature Matrix:
 [[1 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 0]
 [0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1]]
BoW Feature Names:
 ['and' 'anyone' 'disappointing' 'fantastic' 'film' 'good' 'it' 'loved'
 'movie' 'not' 'really' 'recommend' 'terrible' 'the' 'to' 'was' 'wouldn']
TF-IDF Feature Matrix:
 [[0.41074684 0.         0.         0.41074684 0.         0.
  0.2425937  0.41074684 0.41074684 0.         0.         0.
  0.         0.41074684 0.         0.31238356 0.        ]
 [0.         0.         0.45050407 0.         0.45050407 0.
  0.26607496 0.         0.         0.         0.45050407 0.
  0.45050407 0.         0.         0.34261996 0.        ]
 [0.         0.39687454 0.         0.         0.         0.39687454
  0.2344005  0.         0.         0.39687454 0.         0.39687454
  0.         0.         0.39687454 0.         0.39687454]]
TF-IDF Feature Names:
 ['and' 'anyone' 'disappointing' 'fantastic' 'film' 'good' 'it' 'loved'
 'movie' 'not' 'really' 

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...


Sentiment score for 'The movie was fantastic and I loved it!': {'neg': 0.0, 'neu': 0.391, 'pos': 0.609, 'compound': 0.8313}
Sentiment score for 'It was a terrible film, really disappointing.': {'neg': 0.622, 'neu': 0.378, 'pos': 0.0, 'compound': -0.7645}
Sentiment score for 'Not good, I wouldn't recommend it to anyone.': {'neg': 0.261, 'neu': 0.542, 'pos': 0.197, 'compound': -0.1493}


[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


POS Tags for 'The movie was fantastic and I loved it!': [('The', 'DT'), ('movie', 'NN'), ('was', 'VBD'), ('fantastic', 'JJ'), ('and', 'CC'), ('I', 'PRP'), ('loved', 'VBD'), ('it', 'PRP'), ('!', '.')]
POS Tags for 'It was a terrible film, really disappointing.': [('It', 'PRP'), ('was', 'VBD'), ('a', 'DT'), ('terrible', 'JJ'), ('film', 'NN'), (',', ','), ('really', 'RB'), ('disappointing', 'JJ'), ('.', '.')]
POS Tags for 'Not good, I wouldn't recommend it to anyone.': [('Not', 'RB'), ('good', 'JJ'), (',', ','), ('I', 'PRP'), ('would', 'MD'), ("n't", 'RB'), ('recommend', 'VB'), ('it', 'PRP'), ('to', 'TO'), ('anyone', 'NN'), ('.', '.')]
Bigrams Feature Matrix:
 [[1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 1]]
Bigrams Feature Names:
 ['and loved' 'fantastic and' 'film really' 'good wouldn' 'it to' 'it was'
 'loved it' 'movie was' 'not good' 'really disappointing' 'recommend it'
 'terrible film' 'the movie' 'to anyone' 'was fanta

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [3]:
# You code here (Please add comments in the code):

from sklearn.feature_selection import chi2
import numpy as np

# Creating labels (1: positive, 0: negative)
y = [1, 0, 0]

# Feature selection based on Chi-square  on TF-IDF matrix
chi2_scores, p_values = chi2(X_tfidf, y)

# Ranking features (highest to lowest chi-square score)
ranking_indices = np.argsort(chi2_scores)[::-1]
ranked_features = np.array(tfidf_vectorizer.get_feature_names_out())[ranking_indices]

print("Ranked Features based on Chi-Square Scores:\n", ranked_features)
print("Chi-Square Scores:\n", chi2_scores[ranking_indices])




Ranked Features based on Chi-Square Scores:
 ['movie' 'loved' 'fantastic' 'and' 'the' 'terrible' 'really' 'film'
 'disappointing' 'recommend' 'not' 'good' 'to' 'anyone' 'wouldn' 'was'
 'it']
Chi-Square Scores:
 [8.21493670e-01 8.21493670e-01 8.21493670e-01 8.21493670e-01
 8.21493670e-01 2.25252036e-01 2.25252036e-01 2.25252036e-01
 2.25252036e-01 1.98437270e-01 1.98437270e-01 1.98437270e-01
 1.98437270e-01 1.98437270e-01 1.98437270e-01 6.07683876e-02
 1.57269964e-04]


## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [4]:
# You code here (Please add comments in the code):

from transformers import BertTokenizer, BertModel
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Loading the already pre-trained BERT model and also tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def get_bert_embeddings(text):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze()

# An example of Sample query
query = "The movie was amazing!"

# Extracting BERT embeddings for the queries and texts involved
text_embeddings = [get_bert_embeddings(text) for text in texts]
query_embedding = get_bert_embeddings(query)

# Calculating cosine similarity
cosine_similarities = cosine_similarity(
    [query_embedding],
    [embedding.numpy() for embedding in text_embeddings]
)

# Ranking the texts based on similarity
ranked_indices = np.argsort(cosine_similarities[0])[::-1]
print("Ranked Texts by Similarity:")
for index in ranked_indices:
    print(f"Text: {texts[index]}, Similarity Score: {cosine_similarities[0][index]}")




/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Ranked Texts by Similarity:
Text: The movie was fantastic and I loved it!, Similarity Score: 0.9219447374343872
Text: It was a terrible film, really disappointing., Similarity Score: 0.7067286372184753
Text: Not good, I wouldn't recommend it to anyone., Similarity Score: 0.5351264476776123


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [5]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:


Learning Experience:
While Working on these exercises I understood the basics of text classification and feature extraction. I learned how to get simple but important features in text data which can help in solving real-world problems

Challenges:
How to convert text into numerical features so that the machine learning model can understand and use. Vectorization concepts are very new to me which are important for text analysis.

Relevance to NLP:
The excercises provided are basic to Natural Language Processing. I got to know about important topics like feature extraction, vectorization, and similarity measures, which are very important for NLP tasks like sentiment analysis, document classification, and information retrieval.




'''

'\nPlease write you answer here:\n\n\nLearning Experience:\nWhile Working on these exercises I understood the basics of text classification and feature extraction. I learned how to get simple but important features in text data which can help in solving real-world problems\n\nChallenges:\nHow to convert text into numerical features so that the machine learning model can understand and use. Vectorization concepts are very new to me which are important for text analysis.\n\nRelevance to NLP:\nThe excercises provided are basic to Natural Language Processing. I got to know about important topics like feature extraction, vectorization, and similarity measures, which are very important for NLP tasks like sentiment analysis, document classification, and information retrieval.\n\n\n\n\n'